hepsi: derle çalıştır

derle:
	g++ -I ./include/ -c ./src/Node.cpp -o ./lib/Node.o
	g++ -I ./include/ -c ./src/Dosya.cpp -o ./lib/Dosya.o
	g++ -I ./include/ ./src/main.cpp -o ./bin/uygulama ./lib/Node.o ./lib/Dosya.o
çalıştır:
	./bin/uygulama